# Generated by Django 3.2.7 on 2021-10-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'ordering': ['email']},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='',
        ),
    ]
