# Generated by Django 3.2.7 on 2021-10-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211028_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='developer_role',
            field=models.CharField(choices=[('FRONTEND', 'BACKEND'), ('API_BUILDER', 'UI-DESIGNER'), ('PROJECT-MANAGEMENT', 'MOBILE_DEVELOPPER'), ('ANDRIOD-DEVELOPPER', 'IOS DEVELOPPER')], default='BACKEND', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userid',
            field=models.CharField(default='AB-12345', max_length=8, unique=True),
        ),
    ]
